# This file will be configured in Streamlit Cloud
# Add your Railway backend URL here

API_BASE_URL = "https://your-railway-backend-url.railway.app"

# Note: In Streamlit Cloud, you'll set this in the app dashboard
# Secrets section: API_BASE_URL = "https://your-actual-railway-url.railway.app"